CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(25) NOT NULL,
  "email" varchar(30) NOT NULL,
  "password" varchar(15) UNIQUE NOT NULL,
  "age" int NOT NULL,
  "Id_rol" int NOT NULL
);

CREATE TABLE "courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(15) UNIQUE NOT NULL,
  "description" varchar(20) NOT NULL,
  "Id_category" int NOT NULL,
  "Id_level" int NOT NULL,
  "Id_courses_video" int NOT NULL,
  "Id_teacher" int NOT NULL
);

CREATE TABLE "courses_video" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(15) UNIQUE NOT NULL,
  "url" varchar(30) NOT NULL
);

CREATE TABLE "level" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(15) NOT NULL
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "category" varchar(15) NOT NULL
);

CREATE TABLE "rol" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(25) NOT NULL
);

ALTER TABLE "users" ADD FOREIGN KEY ("Id_rol") REFERENCES "rol" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("Id_category") REFERENCES "categories" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("Id_courses_video") REFERENCES "courses_video" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("Id_level") REFERENCES "level" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("Id_teacher") REFERENCES "users" ("id");
2